name: flutter_corner_shape_example
description: Example app for the flutter_corner_shape package.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_corner_shape:
    path: ../

flutter:
  uses-material-design: true
